from typing import Protocol

from platform_api.domain.entities import Application, Company, CompanyJob, Course, Internship, User


class PlatformRepository(Protocol):
    generation: str

    def create_user(self, **values) -> User: ...
    def save_user(self, user: User) -> User: ...
    def get_user(self, user_id: int) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_registration(self, registration: str) -> User | None: ...
    def get_course(self, code: str) -> Course | None: ...
    def list_courses(self) -> list[Course]: ...
    def list_internships(self) -> list[Internship]: ...
    def get_internship(self, slug: str) -> Internship | None: ...
    def save_internship(self, user_id: int, slug: str) -> None: ...
    def unsave_internship(self, user_id: int, slug: str) -> bool: ...
    def is_saved(self, user_id: int, slug: str) -> bool: ...
    def create_application(self, user_id: int, slug: str, cover_letter: str) -> Application: ...
    def has_application(self, user_id: int, slug: str) -> bool: ...
    def list_applications_for_internship(self, slug: str) -> list[Application]: ...
    def create_company(self, **values) -> Company: ...
    def save_company(self, company: Company) -> Company: ...
    def get_company(self, company_id: int) -> Company | None: ...
    def get_company_by_email(self, email: str) -> Company | None: ...
    def get_company_by_cnpj(self, cnpj: str) -> Company | None: ...
    def list_company_jobs(self, company_id: int) -> list[CompanyJob]: ...
    def get_company_job(self, job_id: int) -> CompanyJob | None: ...
    def create_company_job(self, company_id: int, **values) -> CompanyJob: ...
    def delete_company_job(self, job_id: int) -> bool: ...
