from typing import Protocol

from platform_api.domain.entities import Application, Course, Internship, User


class PlatformRepository(Protocol):
    def create_user(self, **values) -> User: ...
    def get_user(self, user_id: int) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_registration(self, registration: str) -> User | None: ...
    def get_course(self, code: str) -> Course | None: ...
    def list_courses(self) -> list[Course]: ...
    def list_internships(self) -> list[Internship]: ...
    def get_internship(self, slug: str) -> Internship | None: ...
    def save_internship(self, user_id: int, slug: str) -> None: ...
    def unsave_internship(self, user_id: int, slug: str) -> bool: ...
    def is_saved(self, user_id: int, slug: str) -> bool: ...
    def create_application(self, user_id: int, slug: str, cover_letter: str) -> Application: ...
    def has_application(self, user_id: int, slug: str) -> bool: ...
