# Generated by Django 5.2.16 on 2026-07-14 11:59

import django.db.models.deletion
import platform_api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text
import django.db.models.functions.datetime
import django.db.models.lookups


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'usuarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='usuarios_email_check')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(db_column='codigo', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=100)),
            ],
            options={
                'db_table': 'cursos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(db_column='razao_social', max_length=255)),
                ('trade_name', models.CharField(blank=True, db_column='nome_fantasia', max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('phone', models.CharField(blank=True, db_column='telefone_contato', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='endereco', max_length=255, null=True)),
                ('about', models.TextField(blank=True, db_column='descricao_institucional', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('account', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='platform_api.account')),
            ],
            options={
                'db_table': 'empresas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cnpj__regex', '^(?:[0-9]{14}|[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}/[0-9]{4}-[0-9]{2})$')), name='empresas_cnpj_check')],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(db_column='titulo', max_length=255)),
                ('location', models.CharField(db_column='localidade', max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('onsite', 'Presencial'), ('hybrid', 'Híbrido'), ('remote', 'Remoto')], db_column='modalidade', max_length=20)),
                ('weekly_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(44)])),
                ('stipend', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(db_column='descricao')),
                ('requirements', platform_api.models.TextArrayField(blank=True, db_column='requisitos', default=list)),
                ('minimum_semester', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('application_deadline', models.DateField()),
                ('external_application', models.BooleanField(db_column='candidatura_externa', default=False)),
                ('external_url', models.TextField(blank=True, db_column='link_candidatura_externa', null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('company', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='platform_api.company')),
            ],
            options={
                'db_table': 'vagas',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('weekly_hours__gte', 4), ('weekly_hours__lte', 44)), name='vagas_weekly_hours_check'), models.CheckConstraint(condition=models.Q(('minimum_semester__gte', 1), ('minimum_semester__lte', 19)), name='vagas_minimum_semester_check'), models.CheckConstraint(condition=models.Q(('status__in', ('ativa', 'encerrada', 'inativa'))), name='vagas_status_check'), models.CheckConstraint(condition=models.Q(('external_application', False), ('external_url__isnull', False), _connector='OR'), name='vagas_check')],
            },
        ),
        migrations.CreateModel(
            name='InternshipCourse',
            fields=[
                ('pk', models.CompositePrimaryKey('internship_id', 'course_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(db_column='curso_codigo', on_delete=django.db.models.deletion.PROTECT, to='platform_api.course')),
                ('internship', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.CASCADE, to='platform_api.internship')),
            ],
            options={
                'db_table': 'vaga_cursos',
            },
        ),
        migrations.AddField(
            model_name='internship',
            name='eligible_courses',
            field=models.ManyToManyField(related_name='internships', through='platform_api.InternshipCourse', to='platform_api.course'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='nome_completo', max_length=255)),
                ('registration', models.CharField(db_column='matricula', max_length=9, unique=True)),
                ('semester', models.IntegerField(blank=True, db_column='semestre', null=True)),
                ('phone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='cidade', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('account', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='platform_api.account')),
                ('course', models.ForeignKey(db_column='curso_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='platform_api.course')),
            ],
            options={
                'db_table': 'alunos',
                'constraints': [models.CheckConstraint(condition=models.Q(('registration__regex', '^[0-9]{9}$')), name='alunos_matricula_check'), models.CheckConstraint(condition=models.Q(('semester__isnull', True), models.Q(('semester__gte', 1), ('semester__lte', 20)), _connector='OR'), name='alunos_semestre_check')],
            },
        ),
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved', models.BooleanField(db_column='favorita', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_salvamento', db_default=django.db.models.functions.datetime.Now())),
                ('note', models.TextField(blank=True, db_column='observacao', null=True)),
                ('internship', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.PROTECT, related_name='saved_by', to='platform_api.internship')),
                ('student', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_internships', to='platform_api.student')),
            ],
            options={
                'db_table': 'favoritos',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('status', models.CharField(choices=[('submitted', 'Enviada'), ('under_review', 'Em análise'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='data_candidatura', db_default=django.db.models.functions.datetime.Now())),
                ('internship', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='platform_api.internship')),
                ('student', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='platform_api.student')),
            ],
            options={
                'db_table': 'candidaturas',
                'ordering': ('submitted_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('submitted', 'under_review', 'accepted', 'rejected'))), name='candidaturas_status_check'), models.CheckConstraint(condition=models.Q(('cover_letter__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('cover_letter'), 3000), _connector='OR'), name='candidaturas_cover_letter_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedinternship',
            constraint=models.UniqueConstraint(fields=('student', 'internship'), name='favoritos_aluno_id_vaga_id_key'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'internship'), name='candidaturas_aluno_id_vaga_id_key'),
        ),
    ]
