# Generated by Django 5.2.16 on 2026-07-14 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='openings',
            field=models.IntegerField(db_column='quantidade_vagas', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.CheckConstraint(condition=models.Q(('openings__gte', 1), ('openings__lte', 100)), name='quantidade_vagas_entre_1_e_100'),
        ),
    ]
